package com.ruanyun.web.model;
// Generated 2016-1-25 17:35:05 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TAdverInferface generated by hbm2java
 */
@Entity
@Table(name="t_adver_inferface"
)
public class TAdverInferface  implements java.io.Serializable {


     private Integer inferaceId;
     private String parameterType;
     private String parameterTypeName;
     private String parameterName;
     private String adverNum;
     private Integer inferfaceRequestType;
     private String inferfaceType;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;

    public TAdverInferface() {
    }

    public TAdverInferface(String parameterType, String parameterName, String adverNum, Integer inferfaceRequestType, String inferfaceType, String flag1, String flag2, String flag3, String flag4, String flag5) {
       this.parameterType = parameterType;
       this.parameterName = parameterName;
       this.adverNum = adverNum;
       this.inferfaceRequestType = inferfaceRequestType;
       this.inferfaceType = inferfaceType;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="inferace_id", unique=true, nullable=false)
    public Integer getInferaceId() {
        return this.inferaceId;
    }
    
    public void setInferaceId(Integer inferaceId) {
        this.inferaceId = inferaceId;
    }
    
    @Column(name="parameter_type", length=100)
    public String getParameterType() {
        return this.parameterType;
    }
    
    public void setParameterType(String parameterType) {
        this.parameterType = parameterType;
    }
    
    @Column(name="parameter_name", length=100)
    public String getParameterName() {
        return this.parameterName;
    }
    
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }
    
    @Column(name="adver_num", length=100)
    public String getAdverNum() {
        return this.adverNum;
    }
    
    public void setAdverNum(String adverNum) {
        this.adverNum = adverNum;
    }
    
    @Column(name="inferface_request_type")
    public Integer getInferfaceRequestType() {
        return this.inferfaceRequestType;
    }
    
    public void setInferfaceRequestType(Integer inferfaceRequestType) {
        this.inferfaceRequestType = inferfaceRequestType;
    }
    
    @Column(name="inferface_type", length=10)
    public String getInferfaceType() {
		return inferfaceType;
	}

	public void setInferfaceType(String inferfaceType) {
		this.inferfaceType = inferfaceType;
	}

	@Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }
    @Transient
	public String getParameterTypeName() {
		return parameterTypeName;
	}

	public void setParameterTypeName(String parameterTypeName) {
		this.parameterTypeName = parameterTypeName;
	}
    




}


