package com.ruanyun.web.model;
// Generated 2017-1-6 11:47:30 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TAdverAuth generated by hbm2java
 */
@Entity
@Table(name="t_adver_auth")
public class TAdverAuth  implements java.io.Serializable {


     private Integer authId;
     private String commonNum;
     private String commonAuthNum;
     private Integer authType;
     private Integer commonType;
   
     private TSchool school;

    public TAdverAuth() {
    }

    public TAdverAuth(String commonNum, String commonAuthNum, Integer authType, Integer commonType) {
       this.commonNum = commonNum;
       this.commonAuthNum = commonAuthNum;
       this.authType = authType;
       this.commonType = commonType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="auth_id", unique=true, nullable=false)
    public Integer getAuthId() {
        return this.authId;
    }
    
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }
    
    @Column(name="commonNum", length=100)
    public String getCommonNum() {
        return this.commonNum;
    }
    
    public void setCommonNum(String commonNum) {
        this.commonNum = commonNum;
    }
    
    @Column(name="commonAuthNum", length=100)
    public String getCommonAuthNum() {
        return this.commonAuthNum;
    }
    
    public void setCommonAuthNum(String commonAuthNum) {
        this.commonAuthNum = commonAuthNum;
    }
    
    @Column(name="auth_Type")
    public Integer getAuthType() {
        return this.authType;
    }
    
    public void setAuthType(Integer authType) {
        this.authType = authType;
    }
    
    @Column(name="common_type")
    public Integer getCommonType() {
        return this.commonType;
    }
    
    public void setCommonType(Integer commonType) {
        this.commonType = commonType;
    }

    @Transient
    public TSchool getSchool() {
		return school;
	}
    public void setSchool(TSchool school) {
		this.school = school;
	}



}


