package com.ruanyun.web.model;
// Generated 2016-1-21 20:20:09 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TAdverEffectiveInfo generated by hbm2java
 */
@Entity
@Table(name="t_adver_effective_info"
)
public class TAdverEffectiveInfo  implements java.io.Serializable 
{
	private static final long serialVersionUID = 1L;
	private Integer effectiveId;
     private String effectiveNum;
     private String channelNum;
     private String channelName;
     private String adverNum;
     private String adverName;
     private String adverStepNum;
     private String adverStepName;
     private Float score;
     private String ip;
     private String ipName;
     private String userNum;
     private String remark;
     private String phoneSerialNumber;
     private String systemVersion;
     private String imei;
     private String idfa;
     private String openudid;
     private String mac;
     private String phoneModel;
     private String phoneOther;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private Date updatetime;
     private Date createtime;
     private Integer downloadNum;//下载数量
     private Date endtime;//查询结束时间
     private String uniquePrimaryKey;  //回调的唯一主键
     
    public TAdverEffectiveInfo() 
    {
    }

    public TAdverEffectiveInfo(String effectiveNum, String channelNum, String channelName, String adverNum, String adverName, String adverStepNum, String adverStepName, Float score, String ip, String ipName, String userNum, String remark, String phoneSerialNumber, String systemVersion, String imei, String idfa, String openudid, String mac, String phoneModel, String phoneOther, String flag1, String flag2, String flag3, String flag4, String flag5, Date updatetime, Date createtime) {
       this.effectiveNum = effectiveNum;
       this.channelNum = channelNum;
       this.channelName = channelName;
       this.adverNum = adverNum;
       this.adverName = adverName;
       this.adverStepNum = adverStepNum;
       this.adverStepName = adverStepName;
       this.score = score;
       this.ip = ip;
       this.ipName = ipName;
       this.userNum = userNum;
       this.remark = remark;
       this.phoneSerialNumber = phoneSerialNumber;
       this.systemVersion = systemVersion;
       this.imei = imei;
       this.idfa = idfa;
       this.openudid = openudid;
       this.mac = mac;
       this.phoneModel = phoneModel;
       this.phoneOther = phoneOther;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.updatetime = updatetime;
       this.createtime = createtime;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="effective_id", unique=true, nullable=false)
    public Integer getEffectiveId() {
        return this.effectiveId;
    }
    
    public void setEffectiveId(Integer effectiveId) {
        this.effectiveId = effectiveId;
    }
    
    @Column(name="effective_num", length=100)
    public String getEffectiveNum() {
        return this.effectiveNum;
    }
    
    public void setEffectiveNum(String effectiveNum) {
        this.effectiveNum = effectiveNum;
    }
    
    @Column(name="channel_num", length=100)
    public String getChannelNum() {
        return this.channelNum;
    }
    
    public void setChannelNum(String channelNum) {
        this.channelNum = channelNum;
    }
    
    @Column(name="channel_name", length=100)
    public String getChannelName() {
        return this.channelName;
    }
    
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }
    
    @Column(name="adver_num", length=100)
    public String getAdverNum() {
        return this.adverNum;
    }
    
    public void setAdverNum(String adverNum) {
        this.adverNum = adverNum;
    }
    
    @Column(name="adver_name", length=100)
    public String getAdverName() {
        return this.adverName;
    }
    
    public void setAdverName(String adverName) {
        this.adverName = adverName;
    }
    
    @Column(name="adver_step_num", length=100)
    public String getAdverStepNum() {
        return this.adverStepNum;
    }
    
    public void setAdverStepNum(String adverStepNum) {
        this.adverStepNum = adverStepNum;
    }
    
    @Column(name="adver_step_name", length=100)
    public String getAdverStepName() {
        return this.adverStepName;
    }
    
    public void setAdverStepName(String adverStepName) {
        this.adverStepName = adverStepName;
    }
    
    @Column(name="score", length=100)
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    
    @Column(name="ip", length=100)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    
    @Column(name="ip_name", length=100)
    public String getIpName() {
        return this.ipName;
    }
    
    public void setIpName(String ipName) {
        this.ipName = ipName;
    }
    
    @Column(name="user_num", length=100)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    
    @Column(name="remark", length=100)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="phone_serial_number", length=100)
    public String getPhoneSerialNumber() {
        return this.phoneSerialNumber;
    }
    
    public void setPhoneSerialNumber(String phoneSerialNumber) {
        this.phoneSerialNumber = phoneSerialNumber;
    }
    
    @Column(name="system_version", length=100)
    public String getSystemVersion() {
        return this.systemVersion;
    }
    
    public void setSystemVersion(String systemVersion) {
        this.systemVersion = systemVersion;
    }
    
    @Column(name="imei", length=100)
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }
    
    @Column(name="idfa", length=100)
    public String getIdfa() {
        return this.idfa;
    }
    
    public void setIdfa(String idfa) {
        this.idfa = idfa;
    }
    
    @Column(name="openudid", length=100)
    public String getOpenudid() {
        return this.openudid;
    }
    
    public void setOpenudid(String openudid) {
        this.openudid = openudid;
    }
    
    @Column(name="mac", length=100)
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }
    
    @Column(name="phone_model", length=100)
    public String getPhoneModel() {
        return this.phoneModel;
    }
    
    public void setPhoneModel(String phoneModel) {
        this.phoneModel = phoneModel;
    }
    
    @Column(name="phone_other", length=1000)
    public String getPhoneOther() {
        return this.phoneOther;
    }
    
    public void setPhoneOther(String phoneOther) {
        this.phoneOther = phoneOther;
    }
    
    @Column(name="flag1", length=1000)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=1000)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=1000)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=1000)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=1000)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatetime", length=19)
    public Date getUpdatetime() {
        return this.updatetime;
    }
    
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createtime", length=19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
	@Transient
	public Integer getDownloadNum() {
		return downloadNum;
	}

	public void setDownloadNum(Integer downloadNum) {
		this.downloadNum = downloadNum;
	}
	@Transient
	public Date getEndtime() {
		return endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}
	@Column(name="unique_primary_key", length=100)
	public String getUniquePrimaryKey() {
		return uniquePrimaryKey;
	}

	public void setUniquePrimaryKey(String uniquePrimaryKey) {
		this.uniquePrimaryKey = uniquePrimaryKey;
	}
	
	



}


