package com.ruanyun.web.model;
// Generated 2016-1-7 13:35:36 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TAreas generated by hbm2java
 */
@Entity
@Table(name="t_areas"
)
public class TAreas  implements java.io.Serializable {


     private int id;
     private String areaid;
     private String area;
     private String cityid;

    public TAreas() {
    }

	
    public TAreas(int id) {
        this.id = id;
    }
    public TAreas(int id, String areaid, String area, String cityid) {
       this.id = id;
       this.areaid = areaid;
       this.area = area;
       this.cityid = cityid;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="areaid", length=50)
    public String getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }
    
    @Column(name="area", length=50)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    
    @Column(name="cityid", length=50)
    public String getCityid() {
        return this.cityid;
    }
    
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }




}


