package com.ruanyun.web.model;
// Generated 2016-4-16 11:39:15 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TArticleInfo generated by hbm2java
 */
@Entity
@Table(name="t_article_info"
)
public class TArticleInfo  implements java.io.Serializable {


     private Integer articleId;
     private String articleNum;
     private String articlePic;
     private String articleDesc;
     private String articleUrl;
     private Integer taskQuantity;
     private Integer forwardQuantity;
     private Float rewardQuantity;
     private Integer status;
     private Integer showForwardQuantity;
     private Date createTime;
     private String createUserNum;
     private String createUserName;
     private String articleContent;
     private String taskDesc;
     private Integer articleType;
     private Integer type;
     
     private String province;
     private String city;
     private Integer schoolId;
     private Integer isAuth;
     
     private String commonAuthNum;//学校编号或者城市编号
     private Integer authType; //1为城市2为学校
     private Integer accessTimes;//文章访问次数

    public TArticleInfo() {
    }

	
    public TArticleInfo(Date createTime) {
        this.createTime = createTime;
    }
    public TArticleInfo(String articleNum, String articlePic, String articleDesc, String articleUrl, Integer taskQuantity, Integer forwardQuantity, Float rewardQuantity, Integer status, Integer showForwardQuantity, Date createTime, String createUserNum, String createUserName) {
       this.articleNum = articleNum;
       this.articlePic = articlePic;
       this.articleDesc = articleDesc;
       this.articleUrl = articleUrl;
       this.taskQuantity = taskQuantity;
       this.forwardQuantity = forwardQuantity;
       this.rewardQuantity = rewardQuantity;
       this.status = status;
       this.showForwardQuantity = showForwardQuantity;
       this.createTime = createTime;
       this.createUserNum = createUserNum;
       this.createUserName = createUserName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="article_id", unique=true, nullable=false)
    public Integer getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
    
    @Column(name="article_num", length=100)
    public String getArticleNum() {
        return this.articleNum;
    }
    
    public void setArticleNum(String articleNum) {
        this.articleNum = articleNum;
    }
    
    @Column(name="article_pic", length=100)
    public String getArticlePic() {
        return this.articlePic;
    }
    
    public void setArticlePic(String articlePic) {
        this.articlePic = articlePic;
    }
    
    @Column(name="article_desc", length=2000)
    public String getArticleDesc() {
        return this.articleDesc;
    }
    
    public void setArticleDesc(String articleDesc) {
        this.articleDesc = articleDesc;
    }
    
    @Column(name="article_url", length=100)
    public String getArticleUrl() {
        return this.articleUrl;
    }
    
    public void setArticleUrl(String articleUrl) {
        this.articleUrl = articleUrl;
    }
    
    @Column(name="task_quantity")
    public Integer getTaskQuantity() {
        return this.taskQuantity;
    }
    
    public void setTaskQuantity(Integer taskQuantity) {
        this.taskQuantity = taskQuantity;
    }
    
    @Column(name="forward_quantity")
    public Integer getForwardQuantity() {
        return this.forwardQuantity;
    }
    
    public void setForwardQuantity(Integer forwardQuantity) {
        this.forwardQuantity = forwardQuantity;
    }
    
    @Column(name="reward_quantity", precision=12, scale=0)
    public Float getRewardQuantity() {
        return this.rewardQuantity;
    }
    
    public void setRewardQuantity(Float rewardQuantity) {
        this.rewardQuantity = rewardQuantity;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    @Column(name="show_forward_quantity")
    public Integer getShowForwardQuantity() {
        return this.showForwardQuantity;
    }
    
    public void setShowForwardQuantity(Integer showForwardQuantity) {
        this.showForwardQuantity = showForwardQuantity;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="create_user_num", length=100)
    public String getCreateUserNum() {
        return this.createUserNum;
    }
    
    public void setCreateUserNum(String createUserNum) {
        this.createUserNum = createUserNum;
    }
    
    @Column(name="create_user_name", length=100)
    public String getCreateUserName() {
        return this.createUserName;
    }
    
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    @Column(name="article_content")
	public String getArticleContent() {
		return articleContent;
	}


	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent;
	}

	@Column(name="task_desc",length=5000)
	public String getTaskDesc() {
		return taskDesc;
	}


	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}

	@Column(name="article_type")
	public Integer getArticleType() {
		return articleType;
	}


	public void setArticleType(Integer articleType) {
		this.articleType = articleType;
	}

	@Transient
	public Integer getType() {
		return type;
	}


	public void setType(Integer type) {
		this.type = type;
	}

@Column(name="province")
	public String getProvince() {
		return province;
	}


	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name="city")
	public String getCity() {
		return city;
	}


	public void setCity(String city) {
		this.city = city;
	}

	@Column(name="school_id")
	public Integer getSchoolId() {
		return schoolId;
	}


	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Transient
	public String getCommonAuthNum() {
		return commonAuthNum;
	}


	public void setCommonAuthNum(String commonAuthNum) {
		this.commonAuthNum = commonAuthNum;
	}

	@Transient
	public Integer getAuthType() {
		return authType;
	}


	public void setAuthType(Integer authType) {
		this.authType = authType;
	}
	
	@Column(name="is_auth")
	public Integer getIsAuth() {
		return isAuth;
	}
	public void setIsAuth(Integer isAuth) {
		this.isAuth = isAuth;
	}
	
	@Column(name="access_times")
	public Integer getAccessTimes() {
		return accessTimes;
	}
	public void setAccessTimes(Integer accessTimes) {
		this.accessTimes = accessTimes;
	}
	
	
    
}


