package com.ruanyun.web.model;
// Generated 2016-1-22 21:14:38 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TChannelAdverUser generated by hbm2java
 */
@Entity
@Table(name="t_channel_adver_user"
)
public class TChannelAdverUser  implements java.io.Serializable {


     private Integer adverUserId;
     private String adverUserNum;
     private String adverNum;
     private String userNum;
     private Integer adverStepNumCount;
     private Integer adverStepNumCurrent;
     private Integer adverUserStatus;
     private String phoneSerialNumber;
     private Date updatetime;
     private Date createtime;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;

    public TChannelAdverUser() {
    }

    public TChannelAdverUser(String adverUserNum, String adverNum, String userNum, Integer adverStepNumCount, Integer adverStepNumCurrent, Integer adverUserStatus, String phoneSerialNumber, Date updatetime, Date createtime, String flag1, String flag2, String flag3, String flag4, String flag5) {
       this.adverUserNum = adverUserNum;
       this.adverNum = adverNum;
       this.userNum = userNum;
       this.adverStepNumCount = adverStepNumCount;
       this.adverStepNumCurrent = adverStepNumCurrent;
       this.adverUserStatus = adverUserStatus;
       this.phoneSerialNumber = phoneSerialNumber;
       this.updatetime = updatetime;
       this.createtime = createtime;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="adver_user_id", unique=true, nullable=false)
    public Integer getAdverUserId() {
        return this.adverUserId;
    }
    
    public void setAdverUserId(Integer adverUserId) {
        this.adverUserId = adverUserId;
    }
    
    @Column(name="adver_user_num", length=100)
    public String getAdverUserNum() {
        return this.adverUserNum;
    }
    
    public void setAdverUserNum(String adverUserNum) {
        this.adverUserNum = adverUserNum;
    }
    
    @Column(name="adver_num", length=100)
    public String getAdverNum() {
        return this.adverNum;
    }
    
    public void setAdverNum(String adverNum) {
        this.adverNum = adverNum;
    }
    
    @Column(name="user_num", length=100)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    
    @Column(name="adver_step_num_count")
    public Integer getAdverStepNumCount() {
        return this.adverStepNumCount;
    }
    
    public void setAdverStepNumCount(Integer adverStepNumCount) {
        this.adverStepNumCount = adverStepNumCount;
    }
    
    @Column(name="adver_step_num_current")
    public Integer getAdverStepNumCurrent() {
        return this.adverStepNumCurrent;
    }
    
    public void setAdverStepNumCurrent(Integer adverStepNumCurrent) {
        this.adverStepNumCurrent = adverStepNumCurrent;
    }
    
    @Column(name="adver_user_status")
    public Integer getAdverUserStatus() {
        return this.adverUserStatus;
    }
    
    public void setAdverUserStatus(Integer adverUserStatus) {
        this.adverUserStatus = adverUserStatus;
    }
    
    @Column(name="phone_serial_number", length=100)
    public String getPhoneSerialNumber() {
        return this.phoneSerialNumber;
    }
    
    public void setPhoneSerialNumber(String phoneSerialNumber) {
        this.phoneSerialNumber = phoneSerialNumber;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updatetime", length=19)
    public Date getUpdatetime() {
        return this.updatetime;
    }
    
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createtime", length=19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }




}


