package com.ruanyun.web.model;
// Generated 2016-1-16 9:23:35 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TChannelAdverStepUser generated by hbm2java
 */
@Entity
@Table(name="t_channel_adver_step_user"
)
public class TChannelAdverStepUser  implements java.io.Serializable {


     private Integer adverUserStepId;
     private String adverUserStepNum;
     private String channelNum;
     private String adverNum;
     private String adverName;
     private String adverStepNum;
     private String adverStepName;
     private Integer adverUserStepStatus;
     private String ipName;
     private String ip;
     private String phoneSerialNumber;
     private String systemVersion;
     private String imei;
     private String idfa;
     private String openudid;
     private String mac;
     private String phoneModel;
     private String phoneOther;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String userAppNum;
     private Date createtime;
     private Date updatetime;
     

    public TChannelAdverStepUser() {
    }

    public TChannelAdverStepUser(String adverNum, String adverStepNum, Integer adverUserStepStatus, String ipName, String ip, String phoneSerialNumber, String systemVersion, String imei, String idfa, String openudid, String mac, String phoneModel, String phoneOther, String flag1, String flag2, String flag3, String flag4, String flag5, String userAppNum) {
       this.adverNum = adverNum;
       this.adverStepNum = adverStepNum;
       this.adverUserStepStatus = adverUserStepStatus;
       this.ipName = ipName;
       this.ip = ip;
       this.phoneSerialNumber = phoneSerialNumber;
       this.systemVersion = systemVersion;
       this.imei = imei;
       this.idfa = idfa;
       this.openudid = openudid;
       this.mac = mac;
       this.phoneModel = phoneModel;
       this.phoneOther = phoneOther;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.userAppNum = userAppNum;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="adver_user_step_id", unique=true, nullable=false)
    public Integer getAdverUserStepId() {
        return this.adverUserStepId;
    }
    
    public void setAdverUserStepId(Integer adverUserStepId) {
        this.adverUserStepId = adverUserStepId;
    }
    
    @Column(name="adver_num", length=100)
    public String getAdverNum() {
        return this.adverNum;
    }
    
    public void setAdverNum(String adverNum) {
        this.adverNum = adverNum;
    }
    
    @Column(name="adver_step_num", length=100)
    public String getAdverStepNum() {
        return this.adverStepNum;
    }
    
    public void setAdverStepNum(String adverStepNum) {
        this.adverStepNum = adverStepNum;
    }
    
    @Column(name="adver_user_step_status")
    public Integer getAdverUserStepStatus() {
        return this.adverUserStepStatus;
    }
    
    public void setAdverUserStepStatus(Integer adverUserStepStatus) {
        this.adverUserStepStatus = adverUserStepStatus;
    }
    
    @Column(name="ip_name", length=100)
    public String getIpName() {
        return this.ipName;
    }
    
    public void setIpName(String ipName) {
        this.ipName = ipName;
    }
    
    @Column(name="ip", length=100)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    
    @Column(name="phone_serial_number", length=100)
    public String getPhoneSerialNumber() {
        return this.phoneSerialNumber;
    }
    
    public void setPhoneSerialNumber(String phoneSerialNumber) {
        this.phoneSerialNumber = phoneSerialNumber;
    }
    
    @Column(name="system_version", length=100)
    public String getSystemVersion() {
        return this.systemVersion;
    }
    
    public void setSystemVersion(String systemVersion) {
        this.systemVersion = systemVersion;
    }
    
    @Column(name="imei", length=100)
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }
    
    @Column(name="idfa", length=100)
    public String getIdfa() {
        return this.idfa;
    }
    
    public void setIdfa(String idfa) {
        this.idfa = idfa;
    }
    
    @Column(name="openudid", length=100)
    public String getOpenudid() {
        return this.openudid;
    }
    
    public void setOpenudid(String openudid) {
        this.openudid = openudid;
    }
    
    @Column(name="mac", length=100)
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }
    
    @Column(name="phone_model", length=100)
    public String getPhoneModel() {
        return this.phoneModel;
    }
    
    public void setPhoneModel(String phoneModel) {
        this.phoneModel = phoneModel;
    }
    
    @Column(name="phone_other", length=1000)
    public String getPhoneOther() {
        return this.phoneOther;
    }
    
    public void setPhoneOther(String phoneOther) {
        this.phoneOther = phoneOther;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }
    
    @Column(name="user_app_num", length=100)
    public String getUserAppNum() {
        return this.userAppNum;
    }
    
    public void setUserAppNum(String userAppNum) {
        this.userAppNum = userAppNum;
    }
    
    @Column(name="channel_num", length=100)
	public String getChannelNum() {
		return channelNum;
	}

	public void setChannelNum(String channelNum) {
		this.channelNum = channelNum;
	}
    
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatetime", length = 19)
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	@Column(name = "adver_user_step_num")
	public String getAdverUserStepNum() {
		return adverUserStepNum;
	}

	public void setAdverUserStepNum(String adverUserStepNum) {
		this.adverUserStepNum = adverUserStepNum;
	}
	 @Column(name="adver_name", length=100)
	public String getAdverName() {
		return adverName;
	}

	public void setAdverName(String adverName) {
		this.adverName = adverName;
	}
	 @Column(name="adver_step_name", length=100)
	public String getAdverStepName() {
		return adverStepName;
	}

	public void setAdverStepName(String adverStepName) {
		this.adverStepName = adverStepName;
	}
	
	
	    
	    
}


