package com.ruanyun.web.model;
// Generated 2017-1-20 10:25:16 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLoginIp generated by hbm2java
 */
@Entity
@Table(name="t_login_ip"
)
public class TLoginIp  implements java.io.Serializable {


     private Integer id;
     private String logNum;
     private String logIp;
     private Date loginTime;
     
    public TLoginIp() {
    }

    public TLoginIp(String logNum, String logIp, Date loginTime) {
       this.logNum = logNum;
       this.logIp = logIp;
       this.loginTime = loginTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="log_num", length=20)
    public String getLogNum() {
        return this.logNum;
    }
    
    public void setLogNum(String logNum) {
        this.logNum = logNum;
    }
    
    @Column(name="log_ip", length=100)
    public String getLogIp() {
        return this.logIp;
    }
    
    public void setLogIp(String logIp) {
        this.logIp = logIp;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="login_time", length=19)
    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }




}


