package com.ruanyun.web.model;
// Generated 2016-4-29 14:02:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TNotice generated by hbm2java
 */
@Entity
@Table(name="t_notice"
)
public class TNotice  implements java.io.Serializable {


     private Integer noticeId;
     private String title;
     private String content;
     private Date createDate;

    public TNotice() {
    }

    public TNotice(String title, String content, Date createDate) {
       this.title = title;
       this.content = content;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="notice_id", unique=true, nullable=false)
    public Integer getNoticeId() {
        return this.noticeId;
    }
    
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }
    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="content", length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


