package com.ruanyun.web.model;
// Generated 2016-1-18 13:52:46 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPic generated by hbm2java
 */
@Entity
@Table(name="t_pic"
)
public class TPic  implements java.io.Serializable {


     private Integer picId;
     private String picNum;
     private String picPath;
     private String picType;
     private String picContentUrl;
     private Date createtime;
     private Integer picStatus;
     private String picPosition;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;

    public TPic() {
    }

    public TPic(String picNum, String picPath, String picType, String picContentUrl, Date createtime, Integer picStatus, String picPosition, String flag1, String flag2, String flag3, String flag4, String flag5) {
       this.picNum = picNum;
       this.picPath = picPath;
       this.picType = picType;
       this.picContentUrl = picContentUrl;
       this.createtime = createtime;
       this.picStatus = picStatus;
       this.picPosition = picPosition;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="pic_id", unique=true, nullable=false)
    public Integer getPicId() {
        return this.picId;
    }
    
    public void setPicId(Integer picId) {
        this.picId = picId;
    }
    
    @Column(name="pic_num", length=100)
    public String getPicNum() {
        return this.picNum;
    }
    
    public void setPicNum(String picNum) {
        this.picNum = picNum;
    }
    
    @Column(name="pic_path", length=200)
    public String getPicPath() {
        return this.picPath;
    }
    
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }
    
    @Column(name="pic_type", length=100)
    public String getPicType() {
        return this.picType;
    }
    
    public void setPicType(String picType) {
        this.picType = picType;
    }
    
    @Column(name="pic_content_url", length=1500)
    public String getPicContentUrl() {
        return this.picContentUrl;
    }
    
    public void setPicContentUrl(String picContentUrl) {
        this.picContentUrl = picContentUrl;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createtime", length=19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    @Column(name="pic_status")
    public Integer getPicStatus() {
        return this.picStatus;
    }
    
    public void setPicStatus(Integer picStatus) {
        this.picStatus = picStatus;
    }
    
    @Column(name="pic_position", length=100)
    public String getPicPosition() {
        return this.picPosition;
    }
    
    public void setPicPosition(String picPosition) {
        this.picPosition = picPosition;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }




}


