package com.ruanyun.web.model;
// Generated 2016-3-2 11:21:44 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TRedPackageLottery generated by hbm2java
 */
@Entity
@Table(name="t_red_package_lottery"
)
public class TRedPackageLottery  implements java.io.Serializable {


     private Integer lotteryId;
     private String lotteryNum;
     private String lotteryResult;
     private Float lotteryScore;
     private Integer lotteryStatus;
     private Date createTime;

    public TRedPackageLottery() {
    }

    public TRedPackageLottery(String lotteryNum, String lotteryResult, Float lotteryScore, Integer lotteryStatus, Date createTime) {
       this.lotteryNum = lotteryNum;
       this.lotteryResult = lotteryResult;
       this.lotteryScore = lotteryScore;
       this.lotteryStatus = lotteryStatus;
       this.createTime = createTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="lottery_id", unique=true, nullable=false)
    public Integer getLotteryId() {
        return this.lotteryId;
    }
    
    public void setLotteryId(Integer lotteryId) {
        this.lotteryId = lotteryId;
    }
    
    @Column(name="lottery_num", length=100)
    public String getLotteryNum() {
        return this.lotteryNum;
    }
    
    public void setLotteryNum(String lotteryNum) {
        this.lotteryNum = lotteryNum;
    }
    
    @Column(name="lottery_result", length=100)
    public String getLotteryResult() {
        return this.lotteryResult;
    }
    
    public void setLotteryResult(String lotteryResult) {
        this.lotteryResult = lotteryResult;
    }
    
    @Column(name="lottery_score", precision=12, scale=0)
    public Float getLotteryScore() {
        return this.lotteryScore;
    }
    
    public void setLotteryScore(Float lotteryScore) {
        this.lotteryScore = lotteryScore;
    }
    
    @Column(name="lottery_status")
    public Integer getLotteryStatus() {
        return this.lotteryStatus;
    }
    
    public void setLotteryStatus(Integer lotteryStatus) {
        this.lotteryStatus = lotteryStatus;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


