package com.ruanyun.web.model;

// Generated 2016-1-5 21:43:29 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TShopGoods generated by hbm2java
 */
@Entity
@Table(name = "t_shop_goods")
public class TShopGoods implements java.io.Serializable {

	private Integer goodId;
	private String goodNum;
	private String shopNum;
	private String goodImg;
	private String goodName;
	private Float goodPrice;
	private String goodDesc;
	private String flag1;
	private String flag2;
	private String flag3;
	private String flag4;
	private String flag5;
	private String goodType;
	private String exchangeCodeType;//兑换码生成方式

	public TShopGoods() {
	}

	public TShopGoods(String goodNum, String shopNum, String goodImg,
			String goodName, String goodDesc, String flag1, String flag2,
			String flag3, String flag4, String flag5) {
		this.goodNum = goodNum;
		this.shopNum = shopNum;
		this.goodImg = goodImg;
		this.goodName = goodName;

		this.goodDesc = goodDesc;
		this.flag1 = flag1;
		this.flag2 = flag2;
		this.flag3 = flag3;
		this.flag4 = flag4;
		this.flag5 = flag5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "good_id", unique = true, nullable = false)
	public Integer getGoodId() {
		return this.goodId;
	}

	public void setGoodId(Integer goodId) {
		this.goodId = goodId;
	}

	@Column(name = "good_num", length = 100)
	public String getGoodNum() {
		return this.goodNum;
	}

	public void setGoodNum(String goodNum) {
		this.goodNum = goodNum;
	}

	@Column(name = "shop_num", length = 100)
	public String getShopNum() {
		return this.shopNum;
	}

	public void setShopNum(String shopNum) {
		this.shopNum = shopNum;
	}

	@Column(name = "good_img", length = 100)
	public String getGoodImg() {
		return this.goodImg;
	}

	public void setGoodImg(String goodImg) {
		this.goodImg = goodImg;
	}

	@Column(name = "good_name", length = 100)
	public String getGoodName() {
		return this.goodName;
	}

	public void setGoodName(String goodName) {
		this.goodName = goodName;
	}

	@Column(name = "good_price")
	public Float getGoodPrice() {
		return goodPrice;
	}

	public void setGoodPrice(Float goodPrice) {
		this.goodPrice = goodPrice;
	}

	@Column(name = "good_desc", length = 100)
	public String getGoodDesc() {
		return this.goodDesc;
	}

	public void setGoodDesc(String goodDesc) {
		this.goodDesc = goodDesc;
	}

	@Column(name = "flag1", length = 100)
	public String getFlag1() {
		return this.flag1;
	}

	public void setFlag1(String flag1) {
		this.flag1 = flag1;
	}

	@Column(name = "flag2", length = 100)
	public String getFlag2() {
		return this.flag2;
	}

	public void setFlag2(String flag2) {
		this.flag2 = flag2;
	}

	@Column(name = "flag3", length = 100)
	public String getFlag3() {
		return this.flag3;
	}

	public void setFlag3(String flag3) {
		this.flag3 = flag3;
	}

	@Column(name = "flag4", length = 100)
	public String getFlag4() {
		return this.flag4;
	}

	public void setFlag4(String flag4) {
		this.flag4 = flag4;
	}

	@Column(name = "flag5", length = 100)
	public String getFlag5() {
		return this.flag5;
	}

	public void setFlag5(String flag5) {
		this.flag5 = flag5;
	}

	@Column(name = "good_type")
	public String getGoodType() {
		return goodType;
	}

	public void setGoodType(String goodType) {
		this.goodType = goodType;
	}
	@Column(name = "exchange_code_type")
	public String getExchangeCodeType() {
		return exchangeCodeType;
	}

	public void setExchangeCodeType(String exchangeCodeType) {
		this.exchangeCodeType = exchangeCodeType;
	}

}
