package com.ruanyun.web.model;
// Generated 2016-1-5 21:43:29 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TShopsInfo generated by hbm2java
 */
@Entity
@Table(name="t_shops_info"
)
public class TShopsInfo  implements java.io.Serializable {


     private Integer shopId;
     private String shopNum;
     private String shopName;
     private String shopAddress;
     private String shopDesc;
     private String provinceid;
     private String citiesid;
     private String areaid;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String loginName;
     
     @Transient
     public String getLoginName() {
		return loginName;
	}
     public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
    public TShopsInfo() {
    }

    public TShopsInfo(String shopNum, String shopName, String shopAddress, String shopDesc, String provinceid, String citiesid, String areaid, String flag1, String flag2, String flag3, String flag4, String flag5) {
       this.shopNum = shopNum;
       this.shopName = shopName;
       this.shopAddress = shopAddress;
       this.shopDesc = shopDesc;
       this.provinceid = provinceid;
       this.citiesid = citiesid;
       this.areaid = areaid;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="shop_id", unique=true, nullable=false)
    public Integer getShopId() {
		return shopId;
	}
     public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}
    
    @Column(name="shop_num", length=100)
    public String getShopNum() {
        return this.shopNum;
    }
    
    public void setShopNum(String shopNum) {
        this.shopNum = shopNum;
    }
    
    @Column(name="shop_name", length=100)
    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
    
    @Column(name="shop_address", length=100)
    public String getShopAddress() {
        return this.shopAddress;
    }
    
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress;
    }
    
    @Column(name="shop_desc", length=100)
    public String getShopDesc() {
        return this.shopDesc;
    }
    
    public void setShopDesc(String shopDesc) {
        this.shopDesc = shopDesc;
    }
    
    @Column(name="provinceid", length=100)
    public String getProvinceid() {
        return this.provinceid;
    }
    
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }
    
    @Column(name="citiesid", length=100)
    public String getCitiesid() {
        return this.citiesid;
    }
    
    public void setCitiesid(String citiesid) {
        this.citiesid = citiesid;
    }
    
    @Column(name="areaid", length=100)
    public String getAreaid() {
        return this.areaid;
    }
    
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }




}


