package com.ruanyun.web.model;
// Generated 2016-1-5 21:43:29 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ruanyun.common.cache.impl.PublicCache;

/**
 * TUserLevelRate generated by hbm2java
 */
@Entity
@Table(name="t_user_level_rate"
)
public class TUserLevelRate  implements java.io.Serializable {


     private Integer levelRateId;
     private String levelNum;
     private Integer levelRate;
     private Integer rateType;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String rateName;
     
    public TUserLevelRate() {
    }

    public TUserLevelRate(String levelNum, Integer levelRate, Integer rateType, String flag1, String flag2, String flag3, String flag4, String flag5) {
       this.levelNum = levelNum;
       this.levelRate = levelRate;
       this.rateType = rateType;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="level_rate_id", unique=true, nullable=false)
    public Integer getLevelRateId() {
        return this.levelRateId;
    }
    
    public void setLevelRateId(Integer levelRateId) {
        this.levelRateId = levelRateId;
    }
    
    @Column(name="level_num", length=100)
    public String getLevelNum() {
        return this.levelNum;
    }
    
    public void setLevelNum(String levelNum) {
        this.levelNum = levelNum;
    }
    
    @Column(name="level_rate")
    public Integer getLevelRate() {
        return this.levelRate;
    }
    
    public void setLevelRate(Integer levelRate) {
        this.levelRate = levelRate;
    }
    
    @Column(name="rate_type")
    public Integer getRateType() {
        return this.rateType;
    }
    
    public void setRateType(Integer rateType) {
        this.rateType = rateType;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }
    @Transient
	public String getRateName() {
    	rateName=PublicCache.getItemName("LEVEL_RATE_TYPE", this.rateType.toString());
		return rateName;
	}

	public void setRateName(String rateName) {
		this.rateName = rateName;
	}




}


