package com.ruanyun.web.model;
// Generated 2016-1-23 16:16:07 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUserSign generated by hbm2java
 */
@Entity
@Table(name="t_user_sign"
)
public class TUserSign  implements java.io.Serializable {


     private Integer signId;
     private String signNum;
     private String userNum;
     private String signTime;
     private Date createtime;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private Float signScore;

    public TUserSign() {
    }

    public TUserSign(String signNum, String userNum, String signTime, Date createtime, String flag1, String flag2, String flag3, String flag4, String flag5, Float signScore) {
       this.signNum = signNum;
       this.userNum = userNum;
       this.signTime = signTime;
       this.createtime = createtime;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.signScore = signScore;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="sign_id", unique=true, nullable=false)
    public Integer getSignId() {
        return this.signId;
    }
    
    public void setSignId(Integer signId) {
        this.signId = signId;
    }
    
    @Column(name="sign_num", length=100)
    public String getSignNum() {
        return this.signNum;
    }
    
    public void setSignNum(String signNum) {
        this.signNum = signNum;
    }
    
    @Column(name="user_num", length=100)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    
    @Column(name="sign_time", length=200)
    public String getSignTime() {
        return this.signTime;
    }
    
    public void setSignTime(String signTime) {
        this.signTime = signTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createtime", length=19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }
    
    @Column(name="sign_score", precision=12, scale=0)
    public Float getSignScore() {
        return this.signScore;
    }
    
    public void setSignScore(Float signScore) {
        this.signScore = signScore;
    }




}


