package com.ruanyun.web.model;
// Generated 2016-1-16 16:06:25 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUserScore generated by hbm2java
 */
@Entity
@Table(name="t_user_score"
)
public class TUserScore  implements java.io.Serializable 
{
     private Integer userScoreId;
     private String userNum;
     private Float scoreDay;//今日分数
     private Float score;
     private Float scoreSum;
     private Integer type;
     private Integer apprenticeCountDay;
     private Integer apprenticeCount;
     private Float apprenticeScoreDay;
     private Float apprenticeScore;
     private String userLevelNum; //用户等级编号
     private String userNick;//用户昵称
     private String rankingNum;//排名
     private String  headImg;//用户头像
     private String  levelName;//等级名称
     private Integer haveRedPackageDay;//今日已抢红包数量
     private Integer redPackageCountDay;//今日可以抢红包数量
     private Float redPackageScoreDay;//今日红包奖励
     private Float redPackageScoreCount;//红包总奖励
     
    public TUserScore() {
    }

    public TUserScore(String userNum, Float scoreDay, Float score, Float scoreSum, Integer type) {
       this.userNum = userNum;
       this.scoreDay = scoreDay;
       this.score = score;
       this.scoreSum = scoreSum;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_score_id", unique=true, nullable=false)
    public Integer getUserScoreId() {
        return this.userScoreId;
    }
    
    public void setUserScoreId(Integer userScoreId) {
        this.userScoreId = userScoreId;
    }
    
    @Column(name="user_num", length=200)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    
    @Column(name="score_day", precision=12, scale=0)
    public Float getScoreDay() {
        return this.scoreDay;
    }
    
    public void setScoreDay(Float scoreDay) {
        this.scoreDay = scoreDay;
    }
    
    @Column(name="score", precision=12, scale=0)
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    
    @Column(name="score_sum", precision=12, scale=0)
    public Float getScoreSum() {
        return this.scoreSum;
    }
    
    public void setScoreSum(Float scoreSum) {
        this.scoreSum = scoreSum;
    }
    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    @Column(name="apprentice_count_day")
	public Integer getApprenticeCountDay() {
		return apprenticeCountDay;
	}

	public void setApprenticeCountDay(Integer apprenticeCountDay) {
		this.apprenticeCountDay = apprenticeCountDay;
	}
	 @Column(name="apprentice_count")
	public Integer getApprenticeCount() {
		return apprenticeCount;
	}

	public void setApprenticeCount(Integer apprenticeCount) {
		this.apprenticeCount = apprenticeCount;
	}
	 @Column(name="apprentice_score_day")
	public Float getApprenticeScoreDay() {
		return apprenticeScoreDay;
	}

	public void setApprenticeScoreDay(Float apprenticeScoreDay) {
		this.apprenticeScoreDay = apprenticeScoreDay;
	}
	 @Column(name="apprentice_score")
	public Float getApprenticeScore() {
		return apprenticeScore;
	}

	public void setApprenticeScore(Float apprenticeScore) {
		this.apprenticeScore = apprenticeScore;
	}
	
	@Column(name="user_level_num")
	public String getUserLevelNum() {
		return userLevelNum;
	}

	public void setUserLevelNum(String userLevelNum) {
		this.userLevelNum = userLevelNum;
	}

	@Transient
	public String getUserNick() {
		return userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}

	@Transient
	public String getRankingNum() {
		return rankingNum;
	}

	public void setRankingNum(String rankingNum) {
		this.rankingNum = rankingNum;
	}
	@Column(name="have_red_package_day")
	public Integer getHaveRedPackageDay() {
		return haveRedPackageDay;
	}

	public void setHaveRedPackageDay(Integer haveRedPackageDay) {
		this.haveRedPackageDay = haveRedPackageDay;
	}
	@Column(name="red_package_count_day")
	public Integer getRedPackageCountDay() {
		return redPackageCountDay;
	}

	public void setRedPackageCountDay(Integer redPackageCountDay) {
		this.redPackageCountDay = redPackageCountDay;
	}
	@Column(name="red_package_score_day")
	public Float getRedPackageScoreDay() {
		return redPackageScoreDay;
	}

	public void setRedPackageScoreDay(Float redPackageScoreDay) {
		this.redPackageScoreDay = redPackageScoreDay;
	}
	@Column(name="red_package_score_count")
	public Float getRedPackageScoreCount() {
		return redPackageScoreCount;
	}

	public void setRedPackageScoreCount(Float redPackageScoreCount) {
		this.redPackageScoreCount = redPackageScoreCount;
	}
	
	@Transient
	public String getHeadImg() {
		return headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}
	@Transient
	public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	




}


