package com.ruanyun.web.model;
// Generated 2016-1-16 16:07:59 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUserScoreInfo generated by hbm2java
 */
@Entity
@Table(name="t_user_score_info"
)
public class TUserScoreInfo  implements java.io.Serializable
{
     private Integer userScoreInfoId;
     private String userScoreInfoNum;
     private Float score;
     private Integer scoreType;
     private String scoreName;
     private String userAppNum;
     private Integer userType;
     private Date scoreTime;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;

    public TUserScoreInfo() {
    }

	
    public TUserScoreInfo(String userScoreInfoNum) {
        this.userScoreInfoNum = userScoreInfoNum;
    }
    public TUserScoreInfo(String userScoreInfoNum, Float score, Integer scoreType, String scoreName, String userAppNum, Integer userType, Date scoreTime, String flag1, String flag2, String flag3, String flag4, String flag5) {
       this.userScoreInfoNum = userScoreInfoNum;
       this.score = score;
       this.scoreType = scoreType;
       this.scoreName = scoreName;
       this.userAppNum = userAppNum;
       this.userType = userType;
       this.scoreTime = scoreTime;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_score_info_id", unique=true, nullable=false)
    public Integer getUserScoreInfoId() {
        return this.userScoreInfoId;
    }
    
    public void setUserScoreInfoId(Integer userScoreInfoId) {
        this.userScoreInfoId = userScoreInfoId;
    }
    
    @Column(name="user_score_info_num", nullable=false, length=100)
    public String getUserScoreInfoNum() {
        return this.userScoreInfoNum;
    }
    
    public void setUserScoreInfoNum(String userScoreInfoNum) {
        this.userScoreInfoNum = userScoreInfoNum;
    }
    
    @Column(name="score", precision=12, scale=0)
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    
    @Column(name="score_type")
    public Integer getScoreType() {
        return this.scoreType;
    }
    
    public void setScoreType(Integer scoreType) {
        this.scoreType = scoreType;
    }
    
    @Column(name="score_name", length=200)
    public String getScoreName() {
        return this.scoreName;
    }
    
    public void setScoreName(String scoreName) {
        this.scoreName = scoreName;
    }
    
    @Column(name="user_app_num", length=100)
    public String getUserAppNum() {
        return this.userAppNum;
    }
    
    public void setUserAppNum(String userAppNum) {
        this.userAppNum = userAppNum;
    }
    
    @Column(name="user_type")
    public Integer getUserType() {
        return this.userType;
    }
    
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="score_time", length=19)
    public Date getScoreTime() {
        return this.scoreTime;
    }
    
    public void setScoreTime(Date scoreTime) {
        this.scoreTime = scoreTime;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }




}


