package com.ruanyun.web.model;
// Generated 2016-1-18 15:18:08 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ruanyun.common.cache.impl.PublicCache;

/**
 * TUserApprentice generated by hbm2java
 */
@Entity
@Table(name="t_user_apprentice"
)
public class TUserApprentice  implements java.io.Serializable {


     private Integer userApprenticeId;
     private String userApprenticeNum;
     private String userNum;
     private String apprenticeUserNum;
     private Float score;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private Date apprenticeTime;
     private Integer userApprenticeType;
     private String userApprenticeName;//徒弟等级名称
     private String userNick;//用户昵称
    public TUserApprentice() {
    }

    public TUserApprentice(String userApprenticeNum, String userNum, String apprenticeUserNum, Float score, String flag1, String flag2, String flag3, String flag4, String flag5, Date apprenticeTime) {
       this.userApprenticeNum = userApprenticeNum;
       this.userNum = userNum;
       this.apprenticeUserNum = apprenticeUserNum;
       this.score = score;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.apprenticeTime = apprenticeTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_apprentice_id", unique=true, nullable=false)
    public Integer getUserApprenticeId() {
        return this.userApprenticeId;
    }
    
    public void setUserApprenticeId(Integer userApprenticeId) {
        this.userApprenticeId = userApprenticeId;
    }
    
    @Column(name="user_apprentice_num", length=100)
    public String getUserApprenticeNum() {
        return this.userApprenticeNum;
    }
    
    public void setUserApprenticeNum(String userApprenticeNum) {
        this.userApprenticeNum = userApprenticeNum;
    }
    
    @Column(name="user_num", length=100)
    public String getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(String userNum) {
        this.userNum = userNum;
    }
    
    @Column(name="apprentice_user_num", length=100)
    public String getApprenticeUserNum() {
        return this.apprenticeUserNum;
    }
    
    public void setApprenticeUserNum(String apprenticeUserNum) {
        this.apprenticeUserNum = apprenticeUserNum;
    }
    
    @Column(name="score", precision=12, scale=0)
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    
    @Column(name="flag1", length=100)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }
    
    @Column(name="flag2", length=100)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }
    
    @Column(name="flag3", length=100)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }
    
    @Column(name="flag4", length=100)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }
    
    @Column(name="flag5", length=100)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="apprentice_time", length=19)
    public Date getApprenticeTime() {
        return this.apprenticeTime;
    }
    
    public void setApprenticeTime(Date apprenticeTime) {
        this.apprenticeTime = apprenticeTime;
    }
    @Column(name="user_apprentice_type", length=100)
	public Integer getUserApprenticeType() {
		return userApprenticeType;
	}

	public void setUserApprenticeType(Integer userApprenticeType) {
		this.userApprenticeType = userApprenticeType;
	}

	@Transient
	public String getUserApprenticeName() {
		userApprenticeName=PublicCache.getItemName("LEVEL_RATE_TYPE", this.userApprenticeType.toString());
		return userApprenticeName;
	}

	public void setUserApprenticeName(String userApprenticeName) {
		this.userApprenticeName = userApprenticeName;
	}
	@Transient
	public String getUserNick() {
		return userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}
    
    




}


