package com.ruanyun.web.model;

// Generated 2016-1-12 11:25:10 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TUserExchange generated by hbm2java
 */
@Entity
@Table(name = "t_user_exchange")
public class TUserExchange implements java.io.Serializable {

	private Integer exchhangeId;
	private String exchangeNum;
	private String exchangeName;
	private Float exchangeScore;
	private String exchangeUserNum;
	private String exchangeGoodsNum;
	private String exchangeGoodsName;
	private Integer exchangeStatus;
	private Date createtime;
	private String exchangeShopNum;
	private String flag1;
	private String flag2;
	private String flag3;
	private String flag4;
	private String flag5;
	private String exchangeCode;// 兑换码
	private String exchangeRemarks;// 兑换备注
	private String exchangeCodeType;//兑换码生成方式
	private String userNick;
	private String zhifubao;
	private String zhifubaoName;
	private String weixin;
	
	
	public TUserExchange() {
	}

	public TUserExchange(String exchangeNum, String exchangeName,
			String exchangeUserNum, String exchangeGoodsNum,
			String exchangeGoodsName, Integer exchangeStatus, Date createtime,
			String exchangeShopNum, String exchangeCode, String flag1,
			String flag2, String flag3, String flag4, String flag5) {
		this.exchangeNum = exchangeNum;
		this.exchangeName = exchangeName;
		this.exchangeUserNum = exchangeUserNum;
		this.exchangeGoodsNum = exchangeGoodsNum;
		this.exchangeGoodsName = exchangeGoodsName;
		this.exchangeStatus = exchangeStatus;
		this.createtime = createtime;
		this.exchangeShopNum = exchangeShopNum;
		this.flag1 = flag1;
		this.flag2 = flag2;
		this.flag3 = flag3;
		this.flag4 = flag4;
		this.flag5 = flag5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "exchhange_id", unique = true, nullable = false)
	public Integer getExchhangeId() {
		return this.exchhangeId;
	}

	public void setExchhangeId(Integer exchhangeId) {
		this.exchhangeId = exchhangeId;
	}

	@Column(name = "exchange_num", length = 100)
	public String getExchangeNum() {
		return this.exchangeNum;
	}

	public void setExchangeNum(String exchangeNum) {
		this.exchangeNum = exchangeNum;
	}

	@Column(name = "exchange_name", length = 100)
	public String getExchangeName() {
		return this.exchangeName;
	}

	public void setExchangeName(String exchangeName) {
		this.exchangeName = exchangeName;
	}

	@Column(name = "exchange_score")
	public Float getExchangeScore() {
		return exchangeScore;
	}

	public void setExchangeScore(Float exchangeScore) {
		this.exchangeScore = exchangeScore;
	}

	@Column(name = "exchange_user_num", length = 100)
	public String getExchangeUserNum() {
		return this.exchangeUserNum;
	}

	public void setExchangeUserNum(String exchangeUserNum) {
		this.exchangeUserNum = exchangeUserNum;
	}

	@Column(name = "exchange_goods_num", length = 100)
	public String getExchangeGoodsNum() {
		return this.exchangeGoodsNum;
	}

	public void setExchangeGoodsNum(String exchangeGoodsNum) {
		this.exchangeGoodsNum = exchangeGoodsNum;
	}

	@Column(name = "exchange_goods_name", length = 100)
	public String getExchangeGoodsName() {
		return this.exchangeGoodsName;
	}

	public void setExchangeGoodsName(String exchangeGoodsName) {
		this.exchangeGoodsName = exchangeGoodsName;
	}

	@Column(name = "exchange_status")
	public Integer getExchangeStatus() {
		return this.exchangeStatus;
	}

	public void setExchangeStatus(Integer exchangeStatus) {
		this.exchangeStatus = exchangeStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Column(name = "exchange_shop_num", length = 100)
	public String getExchangeShopNum() {
		return this.exchangeShopNum;
	}

	public void setExchangeShopNum(String exchangeShopNum) {
		this.exchangeShopNum = exchangeShopNum;
	}

	@Column(name = "flag1", length = 100)
	public String getFlag1() {
		return this.flag1;
	}

	public void setFlag1(String flag1) {
		this.flag1 = flag1;
	}

	@Column(name = "flag2", length = 100)
	public String getFlag2() {
		return this.flag2;
	}

	public void setFlag2(String flag2) {
		this.flag2 = flag2;
	}

	@Column(name = "flag3", length = 100)
	public String getFlag3() {
		return this.flag3;
	}

	public void setFlag3(String flag3) {
		this.flag3 = flag3;
	}

	@Column(name = "flag4", length = 100)
	public String getFlag4() {
		return this.flag4;
	}

	public void setFlag4(String flag4) {
		this.flag4 = flag4;
	}

	@Column(name = "flag5", length = 100)
	public String getFlag5() {
		return this.flag5;
	}

	public void setFlag5(String flag5) {
		this.flag5 = flag5;
	}

	@Column(name = "exchange_code")
	public String getExchangeCode() {
		return exchangeCode;
	}

	public void setExchangeCode(String exchangeCode) {
		this.exchangeCode = exchangeCode;
	}

	@Column(name = "exchange_remarks")
	public String getExchangeRemarks() {
		return exchangeRemarks;
	}

	public void setExchangeRemarks(String exchangeRemarks) {
		this.exchangeRemarks = exchangeRemarks;
	}
	@Column(name = "exchange_code_type")
	public String getExchangeCodeType() {
		return exchangeCodeType;
	}

	public void setExchangeCodeType(String exchangeCodeType) {
		this.exchangeCodeType = exchangeCodeType;
	}
	@Transient
	public String getUserNick() {
		return userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}
	@Column(name="zhifubao")
	public String getZhifubao() {
		return zhifubao;
	}

	public void setZhifubao(String zhifubao) {
		this.zhifubao = zhifubao;
	}
	@Column(name="zhifubao_name")
	public String getZhifubaoName() {
		return zhifubaoName;
	}

	public void setZhifubaoName(String zhifubaoName) {
		this.zhifubaoName = zhifubaoName;
	}
	@Column(name="weixin")
	public String getWeixin() {
		return weixin;
	}

	public void setWeixin(String weixin) {
		this.weixin = weixin;
	}
	
	

	
	
}
