package com.ruanyun.web.model;
// Generated 2016-1-27 15:38:44 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TView generated by hbm2java
 */
@Entity
@Table(name="t_view"
)
public class TView  implements java.io.Serializable {


     private Integer viewId;
     private String viewType;
     private String viewName;
     private String viewContent;

    public TView() {
    }

    public TView(String viewType, String viewName, String viewContent) {
       this.viewType = viewType;
       this.viewName = viewName;
       this.viewContent = viewContent;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="view_id", unique=true, nullable=false)
    public Integer getViewId() {
        return this.viewId;
    }
    
    public void setViewId(Integer viewId) {
        this.viewId = viewId;
    }
    
    @Column(name="view_type")
    public String getViewType() {
        return this.viewType;
    }
    
    public void setViewType(String viewType) {
        this.viewType = viewType;
    }
    
    @Column(name="view_name")
    public String getViewName() {
        return this.viewName;
    }
    
    public void setViewName(String viewName) {
        this.viewName = viewName;
    }
    
    @Column(name="view_content", length=65535)
    public String getViewContent() {
        return this.viewContent;
    }
    
    public void setViewContent(String viewContent) {
        this.viewContent = viewContent;
    }




}


