package com.ruanyun.web.model.sys;
// Generated 2013-11-22 9:55:13 by Hibernate Tools 3.2.2.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name="t_user"
)
public class TUser  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
     private String loginName;
     private String userName;
     private String loginPass;
     private Integer orgId;
     private String unitName;
     private Integer userSex;
     private String userPhone;
     private String userEmail;
     private String address;
     private Integer createCode;
     private Date createDate;
     private Integer userStatus;
     private String accessToken;
     private String userPhoto;
     private String userNum;
     
     @Column(name="user_num")
     public String getUserNum() {
		return userNum;
	}
     public void setUserNum(String userNum) {
		this.userNum = userNum;
	}
     /**
      * 组织名称
      */
     private String orgName;
     
     /**
 	 * 用户类型 在登录时候设置
 	 */
 	private String requestType;

 	/**
 	 * 角色
 	 */
 	private TRole role;
 	/**
 	 * 权限
 	 */
 	private List<TAuthority> auths = new ArrayList<TAuthority>(0);
 	/**
 	 * url
 	 */
 	private List<TAuthority> urls = new ArrayList<TAuthority>(0);
 	/**
 	 * 手机用户登录返回信息
 	 */
 	private String loginError;
 	
 	/**
 	 * 结束时间
 	 */
 	public Date endDate;
 	
    public TUser() {
    }
    
    public TUser(String loginName, String userName, String loginPass, Integer orgId, Integer userSex, String userPhone, String userEmail, Integer createCode, Date createDate, Integer userStatus,String accessToken,String userPhoto) {
       this.loginName = loginName;
       this.userName = userName;
       this.loginPass = loginPass;
       this.orgId = orgId;
       this.userSex = userSex;
       this.userPhone = userPhone;
       this.userEmail = userEmail;
       this.createCode = createCode;
       this.createDate = createDate;
       this.userStatus = userStatus;
       this.accessToken=accessToken;
       this.userPhoto=userPhoto;
    }
   
     public TUser(String loginName,String userNum) {
		 this.userNum=userNum;
    	 this.loginName=loginName;
	}

	@Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    
    @Column(name="login_name", length=100)
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    
    @Column(name="user_name", length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="login_pass", length=100)
    public String getLoginPass() {
        return this.loginPass;
    }
    
    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass;
    }
    
    @Column(name="org_id")
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }
    @Column(name="unit_name",length=200)
    public String getUnitName() {
		return unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	@Column(name="user_sex")
    public Integer getUserSex() {
        return this.userSex;
    }
    
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }
    
    @Column(name="user_phone", length=20)
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    
    @Column(name="user_email", length=100)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    
    @Column(name="address",length=2000)
    public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name="create_code")
    public Integer getCreateCode() {
        return this.createCode;
    }
    
    public void setCreateCode(Integer createCode) {
        this.createCode = createCode;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    @Column(name="user_status")
    public Integer getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }
    
    @Column(name="access_token", length=200)
	public String getAccessToken() {
		return accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

    
	 @Column(name="user_photo", length=200)
	public String getUserPhoto() {
		return userPhoto;
	}

	public void setUserPhoto(String userPhoto) {
		this.userPhoto = userPhoto;
	}

	@Transient
	public String getRequestType() {
		return requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}
	@Transient
	public TRole getRole() {
		return role;
	}

	public void setRole(TRole role) {
		this.role = role;
	}
	@Transient
	public List<TAuthority> getAuths() {
		return auths;
	}

	public void setAuths(List<TAuthority> auths) {
		this.auths = auths;
	}
	@Transient
	public List<TAuthority> getUrls() {
		return urls;
	}

	public void setUrls(List<TAuthority> urls) {
		this.urls = urls;
	}
@Transient
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
	@Transient
	public String getLoginError() {
		return loginError;
	}

	public void setLoginError(String loginError) {
		this.loginError = loginError;
	}
    @Transient
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	
	




}


